### ISSUE TITLE
how to edit the highest level entity?

### ISSUE THREAD

**Issue by henning** [nyergler/nested-formset#4]
Submitting it here as its the only way I see to contact you...

I find the implementation interesting and helpful, just one thing I couldn't yet figure out:
In the documentation and the example you show how to set up an update view for the Block model, but it actually is only for editing objects related to the block, not the block itself. 

Would it work to make the block's properties edtiable in the same view, too? If so, how?

Thanks in advance,
Henning

**Comment by Gwildor** [comment]
I know I'm late to the party, but I'm just leaving this here for others who are needing this as well. I needed both of these things: a basic form of a grandparent instance, and working inlines on a create view.

It was easier than anticipated (thanks to the pointers in this topic and on some other pages), and in the end I ended up with this:

```python
class NestedFormsetsMixin(generic.FormView):
    def get_form_class(self):
        return nestedformset_factory(
            models.GrandParent,
            models.Parent,
            nested_formset=inlineformset_factory(
                models.Parent,
                models.Child,
                extra=1
            ),
            extra=1
        )

    def get_form(self, form_class):
        form_kwargs = self.get_form_kwargs()

        base_form = modelform_factory(models.GrandParent)(**form_kwargs)
        return base_form, form_class(**form_kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        for f in form:
            if not f.is_valid():
                return self.form_invalid(form)

        return self.form_valid(form)

    def form_valid(self, form):
        self.object = form[0].save()

        for f in form[1:]:
            f.instance = self.object
            f.save()

        return HttpResponseRedirect(self.get_success_url())
```

You can use this for both Django's `CreateView` and `UpdateView`. Do note, however, that for the create view, you need to implement `def get_object(self, queryset=None): return None`. This is because I had to fully override the `post` handler for validation of all the forms. In theory (haven't tested this, but made it in a way that it should be possible), you can have multiple (and optionally nested) formsets or forms this way as well: just return more formsets or forms in the `get_form` method.
